bilet33_site:
    resource: "@Bilet33SiteBundle/Resources/config/routing.yml"
    prefix:   /

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /chat
        permanent: true