<?php

namespace Bilet33\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Bilet33\SiteBundle\Entity\Album;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function getOtherAlbum()
    {
        $audioRepository = $this
            ->getEntityManager()
            ->getRepository('Bilet33SiteBundle:Audio');

        $album = new Album();
        $album->setTitle('Другое');
        $album->setShortDescription('Другие записи');

        $audios = $audioRepository->findBy(['albumId' => null], ['number' => 'DESC']);

        foreach ($audios as $audio) {
            $album->addAudio($audio);
        }

        return $album;
    }
}
