<?php

namespace Bilet33\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioRepository extends EntityRepository
{
}
